set-option -g default-terminal "screen-256color"
set-option -g terminal-overrides ",*:RGB"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on      # renumber windows when any is closed
set -g detach-on-destroy off    # don't exit from tmux when closing a session
set -g history-limit 50000
set -sg escape-time 0
set -g set-clipboard on         # use system clipboard
set -g status-position top
set -g default-terminal "${TERM}"
set -g repeat-time 1000
setw -g mode-keys vi

unbind C-b
set -g prefix C-Space
bind Space send-prefix          # hyper+space as prefix

# WINDOW MANAGEMENT
bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U

# -r :: repeat-time
bind -r H resize-pane -L 5 
bind -r L resize-pane -R 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5

bind v split-window -hc "#{pane_current_path}" # split right
bind h split-window -vc "#{pane_current_path}" # split bottom
bind c new-window -c "#{pane_current_path}" \; command-prompt "rename-window %%"  

# Reload config
unbind R 
bind R source-file ~/.config/tmux/tmux.conf \; display-message "Config Reloaded!"

unbind r
bind r command-prompt "rename-window %%"

bind x kill-pane
bind u respawn-pane -k \; display-message "Respawned!"
bind-key -T copy-mode-vi space send-keys -X begin-selection

unbind s
bind-key "s" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 60% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --footer '^a all | ^t tmux | ^g configs | ^x zoxide | ^d tmux kill | ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    # --preview-window 'right:45%' \
    # --preview 'sesh preview {}'
)\""

bind -N "last-session (via sesh) " L run-shell "sesh last"

##### PLUGINS #######
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'alexwforsythe/tmux-which-key'
##### END PLUGINS ####

# simple status bar using catppuccin pallete
set -g status-style bg="#11111b",fg="black",bright
set -g status-left " #[fg=#89b4fa,bright]  #S"
set -g status-left-length 100
set -g status-right " #{user} "

# Theme: status (windows)
set -g window-status-format "#W"
set -g window-status-separator " | "
set -g window-status-current-format "#[fg=#b7bdf8]#W#{?window_zoomed_flag, 󰀚,}"

set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta\#,nobold}"
set -g window-status-bell-style "fg=red,nobold"
set -g status-justify absolute-centre

set -g popup-border-lines rounded
set -g clock-mode-style 12

##### MUST BE LAST #####
run '~/.config/tmux/plugins/tpm/tpm'

