globinclude kitty.d/**/*.conf
term xterm-256color
allow_hyperlinks yes
editor nvim

# terminal bell
enable_audio_bell no

#cursor trail
cursor_trail 2
cursor_trail_decay 0.1 0.6
cursor_shape beam 
cursor_shape_unfocused hollow
# cursor_blink_interval 0.5 linear ease-out

# look and feel
single_window_border_width 2
window_padding_width 10 5 4
window_margin_width 3
hide_window_decorations titlebar-only 
placement_strategy center 

font_size 14.0


# catppuccin
include ./themes/mocha.conf
